Cvecara/Controllers/ArrangementItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cvecara.Data.Data;
using Cvecara.Data.Entities;
using Cvecara.Business.Managers.Contracts;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;

namespace Cvecara.Controllers
{
    [Authorize]
    public class ArrangementItemsController : Controller
    {
        private readonly IArrangementItemManager _arrangementItemManager;
        private readonly IArrangementManager _arrangementManager;
        private readonly IItemManager _itemManager;

        public ArrangementItemsController(IArrangementItemManager arrangementItemManager, 
            IArrangementManager arrangementManager,
            IItemManager itemManager)
        {
            _arrangementItemManager = arrangementItemManager;
            _arrangementManager = arrangementManager;
            _itemManager = itemManager;
        }

        // GET: ArrangementItems
        public IActionResult Index()
        {
            return View(_arrangementItemManager.Get(includes: new List<Expression<Func<ArrangementItem, object>>>{ 
                e => e.Item,
                e => e.Arrangement
            }));
        }

        // GET: ArrangementItems/Details/5
        public IActionResult Details(int arrangementId, int itemId)
        {
            return View(_arrangementItemManager.GetFirst(e => e.ArrangementId == arrangementId && e.ItemId == itemId, 
                includes: new List<Expression<Func<ArrangementItem, object>>>
            {
                e => e.Arrangement,
                e => e.Item
            }));
        }

        // GET: ArrangementItems/Create
        public IActionResult Create()
        {
            ViewData["ArrangementId"] = new SelectList(_arrangementManager.Get(), "Id", "Name");
            ViewData["ItemId"] = new SelectList(_itemManager.Get(), "Id", "Name");
            return View();
        }

        // POST: ArrangementItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ArrangementId,ItemId,Quantity")] ArrangementItem arrangementItem)
        {
            if (ModelState.IsValid)
            {
                _arrangementItemManager.Add(arrangementItem);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArrangementId"] = new SelectList(_arrangementManager.Get(), "Id", "Name", arrangementItem.ArrangementId);
            ViewData["ItemId"] = new SelectList(_itemManager.Get(), "Id", "Name", arrangementItem.ItemId);
            return View(arrangementItem);
        }

        // GET: ArrangementItems/Edit/5
        public IActionResult Edit(int arrangementId, int itemId)
        {
            var arrangementItem = _arrangementItemManager.GetFirst(e => e.ArrangementId == arrangementId && e.ItemId == itemId);

            ViewData["ArrangementId"] = new SelectList(_arrangementManager.Get(), "Id", "Name", arrangementItem.ArrangementId);
            ViewData["ItemId"] = new SelectList(_itemManager.Get(), "Id", "Name", arrangementItem.ItemId);
            return View(arrangementItem);
        }

        // POST: ArrangementItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ArrangementId,ItemId,Quantity")] ArrangementItem arrangementItem)
        {
            if (ModelState.IsValid)
            {
                _arrangementItemManager.Update(arrangementItem);               
                return RedirectToAction(nameof(Index));
            }

            ViewData["ArrangementId"] = new SelectList(_arrangementManager.Get(), "Id", "Name", arrangementItem.ArrangementId);
            ViewData["ItemId"] = new SelectList(_itemManager.Get(), "Id", "Name", arrangementItem.ItemId);
            return View(arrangementItem);
        }

        // GET: ArrangementItems/Delete/5
        public IActionResult Delete(int arrangementId, int itemId)
        {

            var arrangementItem = _arrangementItemManager.GetFirst(e => e.ArrangementId == arrangementId && e.ItemId == itemId,
                includes: new List<Expression<Func<ArrangementItem, object>>>
                {
                    e => e.Arrangement,
                    e => e.Item
                });

            return View(arrangementItem);
        }

        // POST: ArrangementItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed([Bind("ArrangementId,ItemId,Quantity")] ArrangementItem arrangementItem)
        {
            _arrangementItemManager.Remove(arrangementItem.ArrangementId, arrangementItem.ItemId);
            return RedirectToAction(nameof(Index));
        }
    }
}

Cvecara/Controllers/InventoryController.cs
using Cvecara.Business.Managers.Contracts;
using Cvecara.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace Cvecara.Controllers
{
    [Authorize(Roles = Roles.Employee)]
    public class InventoryController : Controller
    {
        private readonly IInventoryManager _inventoryManager;
        private readonly IItemManager _itemManager;

        public InventoryController(IInventoryManager inventoryManager, IItemManager itemManager)
        {
            _inventoryManager = inventoryManager;
            _itemManager = itemManager;
        }
        // GET: InventoryController
        public ActionResult Index()
        {
            var includes = new List<Expression<Func<Inventory, object>>>
            {
                e => e.Item
            };

            return View(_inventoryManager.Get(includes: includes));
        }

        // GET: InventoryController/Create
        public ActionResult Create()
        {
            var inventory = _inventoryManager.Get();
            ViewBag.Items = new SelectList(_itemManager.Get(e => !inventory.Any(x => e.Id == x.Id)), nameof(Item.Id), nameof(Item.Name));
            return View();
        }

        // POST: InventoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Inventory inventoryItem)
        {
            try
            {
                _inventoryManager.Add(inventoryItem);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var inventory = _inventoryManager.Get();
                ViewBag.Items = new SelectList(_itemManager.Get(e => !inventory.Any(x => e.Id == x.Id)), nameof(Item.Id), nameof(Item.Name));
                return View();
            }
        }

        // GET: InventoryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_inventoryManager.GetFirst(e => e.Id == id, new List<Expression<Func<Inventory, object>>>
            {
                e => e.Item
            }));
        }

        // POST: InventoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Inventory inventory)
        {
            try
            {
                _inventoryManager.Update(inventory);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(_inventoryManager.GetFirst(e => e.Id == id, new List<Expression<Func<Inventory, object>>>
                {
                    e => e.Item
                }));
            }
        }

        // GET: InventoryController/Delete/5
        public ActionResult Delete(int id)
        {

            return View(_inventoryManager.GetFirst(e => e.Id == id, new List<Expression<Func<Inventory, object>>>
            {
                e => e.Item
            }));
        }

        // POST: InventoryController/Delete/5
        [HttpPost]
        [ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            try
            {
                _inventoryManager.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(_inventoryManager.GetFirst(e => e.Id == id, new List<Expression<Func<Inventory, object>>>
                {
                    e => e.Item
                }));
            }
        }
    }
}

Cvecara/Controllers/ItemController.cs
using Cvecara.Business.Managers.Contracts;
using Cvecara.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cvecara.Controllers
{
    [Authorize(Roles = Roles.Employee)]
    public class ItemController : Controller
    {
        private readonly IItemManager _manager;

        public ItemController(IItemManager manager)
        {
            _manager = manager;
        }

        // GET: ItemController
        public ActionResult Index()
        {
            return View(_manager.Get());
        }

        // GET: ItemController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ItemController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item item)
        {
            try
            {
                _manager.Add(item);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ItemController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_manager.GetFirst(e => e.Id == id));
        }

        // POST: ItemController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Item item)
        {
            try
            {
                _manager.Update(item);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(_manager.GetFirst(e => e.Id == id));
            }
        }

        // GET: ItemController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_manager.GetFirst(e => e.Id == id));
        }

        // POST: ItemController/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            try
            {
                _manager.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(_manager.GetFirst(e => e.Id == id));
            }
        }
    }
}

Cvecara/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cvecara</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cvecara</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(Roles.Employee))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Stavke</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Index">Inventar</a>
                            </li>

                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ArrangementItems" asp-action="Index">Stavke aranzmana</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cvecara - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>